config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to:'home#index'
  devise_for :users
  mount TicketIt::Engine, at: 'demo'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :ticket_it_tickets, foreign_key: 'resource_id'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, if: :not_unlocked_controllers
  before_action :configure_permitted_parameters, if: :devise_controller?

  def ticketit_user
    current_user
  end
  helper_method :ticketit_user

  def after_sign_in_path_for(resource)
    ticket_it_path
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def not_unlocked_controllers
    if controller_name != 'home'
      true
    else
      false
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
.position-relative.overflow-hidden.p-3.p-md-5.m-md-3.text-center.bg-light
  .col-md-5.p-lg-5.mx-auto.my-5
    %h1.display-5.font-weight-normal Got a Ticket? Get TicketIt.
    %p.lead.font-weight-normal
      You have customers asking questions? We can lend you a hand. Get started with TicketIt today and start reducing your pain.
    = link_to 'Get Started Today', new_user_registration_path, class:'btn btn-outline-secondary'
  .product-device.box-shadow.d-none.d-md-block
  .product-device.product-device-2.box-shadow.d-none.d-md-block
.d-md-flex.flex-md-equal.w-100.my-md-3.pl-md-3
  .bg-dark.mr-md-3.pt-3.px-3.pt-md-5.px-md-5.text-center.text-white.overflow-hidden
    .my-3.py-3
      %h2.display-5 Work Efficiently
      %p.lead
        Filters your tickets as you need them.
        %br
        View just yours or cleanup up the backlog.
    .bg-light.box-shadow.mx-auto{:style => "width: 80%; height: 300px; border-radius: 21px 21px 0 0;"}
      = image_tag('all-tickets.png', class:'rounded img-fluid')
  .bg-light.mr-md-3.pt-3.px-3.pt-md-5.px-md-5.text-center.overflow-hidden
    .my-3.p-3
      %h2.display-5 Another headline
      %p.lead And an even wittier subheading.
    .bg-dark.box-shadow.mx-auto{:style => "width: 80%; height: 300px; border-radius: 21px 21px 0 0;"}
.d-md-flex.flex-md-equal.w-100.my-md-3.pl-md-3
  .bg-light.mr-md-3.pt-3.px-3.pt-md-5.px-md-5.text-center.overflow-hidden
    .my-3.p-3
      %h2.display-5 Another headline
      %p.lead And an even wittier subheading.
    .bg-dark.box-shadow.mx-auto{:style => "width: 80%; height: 300px; border-radius: 21px 21px 0 0;"}
  .bg-primary.mr-md-3.pt-3.px-3.pt-md-5.px-md-5.text-center.text-white.overflow-hidden
    .my-3.py-3
      %h2.display-5 Another headline
      %p.lead And an even wittier subheading.
    .bg-light.box-shadow.mx-auto{:style => "width: 80%; height: 300px; border-radius: 21px 21px 0 0;"}
.d-md-flex.flex-md-equal.w-100.my-md-3.pl-md-3
  .bg-light.mr-md-3.pt-3.px-3.pt-md-5.px-md-5.text-center.overflow-hidden
    .my-3.p-3
      %h2.display-5 Another headline
      %p.lead And an even wittier subheading.
    .bg-white.box-shadow.mx-auto{:style => "width: 80%; height: 300px; border-radius: 21px 21px 0 0;"}
  .bg-light.mr-md-3.pt-3.px-3.pt-md-5.px-md-5.text-center.overflow-hidden
    .my-3.py-3
      %h2.display-5 Another headline
      %p.lead And an even wittier subheading.
    .bg-white.box-shadow.mx-auto{:style => "width: 80%; height: 300px; border-radius: 21px 21px 0 0;"}
.d-md-flex.flex-md-equal.w-100.my-md-3.pl-md-3
  .bg-light.mr-md-3.pt-3.px-3.pt-md-5.px-md-5.text-center.overflow-hidden
    .my-3.p-3
      %h2.display-5 Another headline
      %p.lead And an even wittier subheading.
    .bg-white.box-shadow.mx-auto{:style => "width: 80%; height: 300px; border-radius: 21px 21px 0 0;"}
  .bg-light.mr-md-3.pt-3.px-3.pt-md-5.px-md-5.text-center.overflow-hidden
    .my-3.py-3
      %h2.display-5 Another headline
      %p.lead And an even wittier subheading.
    .bg-white.box-shadow.mx-auto{:style => "width: 80%; height: 300px; border-radius: 21px 21px 0 0;"}

app/views/layouts/_footer.html.haml
%footer.container.py-5
  .row
    .col-12.col-md
      %svg.d-block.mb-2{:fill => "none", :height => "24", :stroke => "currentColor", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "2", :viewbox => "0 0 24 24", :width => "24", :xmlns => "http://www.w3.org/2000/svg"}
        %circle{:cx => "12", :cy => "12", :r => "10"}
        %line{:x1 => "14.31", :x2 => "20.05", :y1 => "8", :y2 => "17.94"}
        %line{:x1 => "9.69", :x2 => "21.17", :y1 => "8", :y2 => "8"}
        %line{:x1 => "7.38", :x2 => "13.12", :y1 => "12", :y2 => "2.06"}
        %line{:x1 => "9.69", :x2 => "3.95", :y1 => "16", :y2 => "6.06"}
        %line{:x1 => "14.31", :x2 => "2.83", :y1 => "16", :y2 => "16"}
        %line{:x1 => "16.62", :x2 => "10.88", :y1 => "12", :y2 => "21.94"}
      %small.d-block.mb-3.text-muted © 2017-2018
    .col-6.col-md
      %h5 Features
      %ul.list-unstyled.text-small
        %li
          %a.text-muted{:href => "#"} Cool stuff
        %li
          %a.text-muted{:href => "#"} Random feature
        %li
          %a.text-muted{:href => "#"} Team feature
        %li
          %a.text-muted{:href => "#"} Stuff for developers
        %li
          %a.text-muted{:href => "#"} Another one
        %li
          %a.text-muted{:href => "#"} Last time
    .col-6.col-md
      %h5 Resources
      %ul.list-unstyled.text-small
        %li
          %a.text-muted{:href => "#"} Resource
        %li
          %a.text-muted{:href => "#"} Resource name
        %li
          %a.text-muted{:href => "#"} Another resource
        %li
          %a.text-muted{:href => "#"} Final resource
    .col-6.col-md
      %h5 Resources
      %ul.list-unstyled.text-small
        %li
          %a.text-muted{:href => "#"} Business
        %li
          %a.text-muted{:href => "#"} Education
        %li
          %a.text-muted{:href => "#"} Government
        %li
          %a.text-muted{:href => "#"} Gaming
    .col-6.col-md
      %h5 About
      %ul.list-unstyled.text-small
        %li
          %a.text-muted{:href => "#"} Team
        %li
          %a.text-muted{:href => "#"} Locations
        %li
          %a.text-muted{:href => "#"} Privacy
        %li
          %a.text-muted{:href => "#"} Terms

app/views/layouts/_header.html.haml
- content_for :logo do
  %svg.d-block{:fill => "none", :height => "24", :stroke => "currentColor", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "2", :viewbox => "0 0 24 24", :width => "24", :xmlns => "http://www.w3.org/2000/svg"}
    %circle{:cx => "12", :cy => "12", :r => "10"}
    %line{:x1 => "14.31", :x2 => "20.05", :y1 => "8", :y2 => "17.94"}
    %line{:x1 => "9.69", :x2 => "21.17", :y1 => "8", :y2 => "8"}
    %line{:x1 => "7.38", :x2 => "13.12", :y1 => "12", :y2 => "2.06"}
    %line{:x1 => "9.69", :x2 => "3.95", :y1 => "16", :y2 => "6.06"}
    %line{:x1 => "14.31", :x2 => "2.83", :y1 => "16", :y2 => "16"}
    %line{:x1 => "16.62", :x2 => "10.88", :y1 => "12", :y2 => "21.94"}

%nav.site-header.sticky-top.py-1
  %div.container.d-flex.flex-column.flex-md-row.justify-content-between
    = link_to (yield :logo), root_path, class:'py-2'
    = link_to 'Features','', class:'py-2 d-none d-md-inline-block'
    = link_to 'Docs','', class:'py-2 d-none d-md-inline-block'
    = link_to 'Support','', class:'py-2 d-none d-md-inline-block'
    = link_to 'Demo',ticket_it_path, class:'py-2 d-none d-md-inline-block'
    - if !current_user
      = link_to 'Sign In',new_user_session_path, class:'py-2 d-none d-md-inline-block'
      = link_to 'Sign Up',new_user_registration_path, class:'py-2 d-none d-md-inline-block'
    - else
      = link_to current_user.name,'', class:'py-2 d-none d-md-inline-block'
      = link_to 'Logout',destroy_user_session_path, method: :delete, class:'py-2 d-none d-md-inline-block'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TicketIt–Sample
    = csrf_meta_tags
    = stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css', integrity:'sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm', crossorigin: 'anonymous'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'https://code.jquery.com/jquery-3.2.1.slim.min.js', integrity: 'sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN', crossorigin: 'anonymous'
    = javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js', integrity: 'sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q', crossorigin: 'anonymous'
    = javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js', integrity: 'sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl', crossorigin: 'anonymous'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body.p-0
    = render partial: 'layouts/header'
    - if notice
      = notice
    - if alert
      = alert
    = yield
    = render partial: 'layouts/footer'

app/views/layouts/ticket_it/_header.html.haml
- content_for :logo do
  %svg.d-block{:fill => "none", :height => "24", :stroke => "currentColor", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "2", :viewbox => "0 0 24 24", :width => "24", :xmlns => "http://www.w3.org/2000/svg"}
    %circle{:cx => "12", :cy => "12", :r => "10"}
    %line{:x1 => "14.31", :x2 => "20.05", :y1 => "8", :y2 => "17.94"}
    %line{:x1 => "9.69", :x2 => "21.17", :y1 => "8", :y2 => "8"}
    %line{:x1 => "7.38", :x2 => "13.12", :y1 => "12", :y2 => "2.06"}
    %line{:x1 => "9.69", :x2 => "3.95", :y1 => "16", :y2 => "6.06"}
    %line{:x1 => "14.31", :x2 => "2.83", :y1 => "16", :y2 => "16"}
    %line{:x1 => "16.62", :x2 => "10.88", :y1 => "12", :y2 => "21.94"}
%nav.navbar.navbar-expand-md.fixed-top.navbar-dark.bg-dark
  = link_to (yield :logo), root_path, class:'navbar-brand'
  %button.navbar-toggler.p-0.border-0{"data-toggle" => "offcanvas", :type => "button"}
    %span.navbar-toggler-icon
  #navbarsExampleDefault.navbar-collapse.offcanvas-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item{class: action_name == 'dashboard' ? 'active' : ''}
        = link_to 'Dashboard', dashboard_tickets_path, class:'nav-link'
      %li.nav-item{class: controller_name == 'tickets' && !['dashboard','kanban'].include?(action_name) ? 'active' : ''}
        = link_to 'Tickets', tickets_path, class:'nav-link'
      %li.nav-item{class: controller_name == 'tickets' && action_name == 'kanban' ? 'active' : ''}
        = link_to 'Kanban', kanban_tickets_path, class:'nav-link'
      %li.nav-item{class: controller_name == 'reporters' ? 'active' : ''}
        = link_to 'Reporters', reporters_path, class:'nav-link'
    %ul.navbar-nav.ml-auto
      %li.nav-item.dropdown.dropdown-right
        %a#dropdown01.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "http://example.com"}
          = ticketit_user.name
        .dropdown-menu{"aria-labelledby" => "dropdown01"}
          = link_to 'Settings', main_app.edit_user_registration_path, method: :delete, class:'dropdown-item'
          = link_to 'Logout', main_app.destroy_user_session_path, method: :delete, class:'dropdown-item'
= yield :secondary_nav

app/views/layouts/ticket_it/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TicketItSample
    = stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css', integrity:'sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm', crossorigin: 'anonymous'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'https://code.jquery.com/jquery-3.2.1.slim.min.js', integrity: 'sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN', crossorigin: 'anonymous'
    = javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js', integrity: 'sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q', crossorigin: 'anonymous'
    = javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js', integrity: 'sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl', crossorigin: 'anonymous'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    'ticket_it/application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'ticket_it/application', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags

  %body.bg-light
    = render partial: 'layouts/ticket_it/header'
    %main.container
      - if notice
        .alert.alert-success.mt-2
          = notice
      - if alert
        .alert.alert-danger.mt-2
          = alert
      = yield
    -#= render partial: 'layouts/footer'

app/views/ticket_it/comments/_comment.html.haml
.media.text-muted.pb-3
  = image_tag 'https://getbootstrap.com/assets/brand/bootstrap-outline.svg', width:'28', height:'28', class:'mr-2 rounded bg-purple'
  .media-body.mb-0.small.ln-125
    .d-block.text-gray-dark
      %strong
        = comment.commenter.name
      | #{comment.created_at.strftime('%B %d, %Y')}
    %p.mb-0
      = comment.content

app/views/ticket_it/comments/create.js.haml
$('.comments').prepend("#{escape_javascript(render @comment)}");
$('form#new_comment')[0].reset();

app/views/ticket_it/reporters/_reporter.html.haml
%tr
  %td= link_to reporter.name, reporter_path(reporter)
  %td= reporter.email
  %td= reporter.position
  %td
    = link_to 'Edit', edit_reporter_path(reporter)

app/views/ticket_it/reporters/index.html.haml
= content_for :secondary_nav do
  .nav-scroller.bg-white.box-shadow
    %nav.nav.nav-underline.justify-content-center

.d-flex.align-items-center.p-3.my-3.text-white-50.bg-purple.rounded.box-shadow
  = image_tag 'https://getbootstrap.com/assets/brand/bootstrap-outline.svg', class:'mr-3', width:'28', height:'28'
  .lh-100
    %h3.mb-0.text-white.lh-100
      All Reporters
  .ml-auto
    = link_to 'New', new_reporter_path, class:'btn text-white p-0'
.my-3.p-3.bg-white.rounded.box-shadow
  %table.table
    %thead
      %tr
        %th Name
        %th Email
        %th Phone
        %th
    %tbody
      - if !@reporters.empty?
        = render @reporters
      - else
        %tr
          %td.text-center{colspan: 6}
            No Reporters to display. #{link_to 'Create one now!', new_reporter_path}

app/views/ticket_it/tickets/_form.html.haml
.my-3.p-3.bg-white.rounded.box-shadow
  = form_for ticket do |f|
    - if !ticket.errors.empty?
      %ul.alert.alert-danger.mt-2.list-unstyled
        - ticket.errors.full_messages.each do |m|
          %li
            = m
    .row
      .col-md-6
        .form-group
          = f.label :number
          = f.text_field :number, class:'form-control'
      .col-md-6
        .form-group
          = f.label :status
          = f.select :status, @ticket.ticket_status.map{|t| [t.humanize, t]},{}, {class:'custom-select'}
    .form-group
      = f.label :name
      = f.text_field :name, class:'form-control'
    .form-group
      = f.label :description
      = f.text_area :description, class:'form-control'
    .row
      .col-md-6
        .form-group
          = f.label :priority
          = f.select :priority, @ticket.ticket_priorities.map{|t| [t.humanize, t]},{prompt: true}, class:'form-control'
      .col-md-6
        .form-group
          = f.label :ticket_type
          = f.select :ticket_type, @ticket.ticket_types.map{|t| [t.humanize, t]},{prompt: true}, class:'form-control'
    .form-group
      = f.label :prefered_contact
      = f.select :prefered_contact, @ticket.ticket_contact.map{|t| [t.humanize, t]},{prompt: true}, class:'form-control'
    = f.submit "#{ticket.persisted? ? 'Update Ticket' : 'Save Ticket'}", class:'btn bg-purple text-white'
    = link_to 'Cancel', tickets_path, class:'btn btn-outline-danger'

app/views/ticket_it/tickets/_ticket.html.haml
%tr
  %td= ticket.number
  %td= link_to ticket.name, ticket_path(ticket)
  %td= ticket.priority.humanize
  %td= ticket.status.humanize
  %td= ticket.ticket_type.humanize
  %td
    = link_to 'Edit', edit_ticket_path(ticket)

app/views/ticket_it/tickets/dashboard.html.haml
.d-flex.align-items-center.p-3.my-3.text-white-50.bg-purple.rounded.box-shadow
  = image_tag 'https://getbootstrap.com/assets/brand/bootstrap-outline.svg', class:'mr-3', width:'28', height:'28'
  .lh-100
    %h3.mb-0.text-white.lh-100
      Dashboard
.row.m-0.d-flex.align-items-center
  -#Sample of metrics {"all"=>1, "new"=>1, "work_in_progress"=>0, "quality_check"=>0, "closed"=>0}
  - @ticket_metrics.each do |m,v|
    .col-md-3.col-12.pl-0
      .my-3.p-3.bg-white.rounded.box-shadow.text-center
        %h3
          = v
        %strong.text-muted
          = m.to_s.humanize

app/views/ticket_it/tickets/edit.html.haml
.d-flex.align-items-center.p-3.my-3.text-white-50.bg-purple.rounded.box-shadow
  = image_tag 'https://getbootstrap.com/assets/brand/bootstrap-outline.svg', class:'mr-3', width:'28', height:'28'
  .lh-100
    %h3.mb-0.text-white.lh-100
      Edit ticket

= render partial: 'form', locals:{ticket: @ticket}

app/views/ticket_it/tickets/index.html.haml
= content_for :secondary_nav do
  .nav-scroller.bg-white.box-shadow
    %nav.nav.nav-underline.justify-content-center
      = link_to "My Tickets&nbsp;&nbsp;<span class='badge badge-pill bg-light align-text-bottom'>&nbsp;#{@tickets.count}&nbsp;</span>".html_safe, tickets_path(filter: :my_tickets), class:"nav-link bg-light #{params[:filter]=='all_tickets' ? nil : 'active'}"
      = link_to 'All Tickets', tickets_path(filter: :all_tickets), class:"nav-link bg-light #{params[:filter]=='all_tickets' ? 'active':nil}"

.d-flex.align-items-center.p-3.my-3.text-white-50.bg-purple.rounded.box-shadow
  = image_tag 'https://getbootstrap.com/assets/brand/bootstrap-outline.svg', class:'mr-3', width:'28', height:'28'
  .lh-100
    %h3.mb-0.text-white.lh-100
      = params[:filter]=='all_tickets' ? 'All Tickets' : 'My Tickets'
  .ml-auto
    = link_to 'New', new_ticket_path, class:'btn text-white p-0'
.my-3.p-3.bg-white.rounded.box-shadow
  %table.table
    %thead
      %tr
        %th Number
        %th Name
        %th Priority
        %th Status
        %th Type
        %th
    %tbody
      - @tickets = (params[:filter]=='all_tickets' ? @all_tickets : @tickets)
      - if @tickets
        = render @tickets
      - else
        %tr
          %td.text-center{colspan: 6}
            No Tickets to display. #{link_to 'Create one now!', new_ticket_path}

app/views/ticket_it/tickets/kanban.html.haml
.d-flex.align-items-center.p-3.my-3.text-white-50.bg-purple.rounded.box-shadow
  = image_tag 'https://getbootstrap.com/assets/brand/bootstrap-outline.svg', class:'mr-3', width:'28', height:'28'
  .lh-100
    %h3.mb-0.text-white.lh-100
      Kanban Board
  .ml-auto
    = link_to 'New', new_ticket_path, class:'btn text-white p-0'
.row.scrollable
  - TicketIt::Ticket.first.ticket_status.each do |s|
    .col-4
      .my-3.p-3.bg-white.rounded.box-shadow
        .text-center
          %h3
            = s.humanize
        %ul
          - if @tickets["#{s}"]
            - @tickets["#{s}"].each do |t|
              %li
                = link_to t.name, tickets_path(t)

app/views/ticket_it/tickets/new.html.haml
.d-flex.align-items-center.p-3.my-3.text-white-50.bg-purple.rounded.box-shadow
  = image_tag 'https://getbootstrap.com/assets/brand/bootstrap-outline.svg', class:'mr-3', width:'28', height:'28'
  .lh-100
    %h3.mb-0.text-white.lh-100
      Create a ticket

= render partial: 'form', locals:{ticket: @ticket}

app/views/ticket_it/tickets/show.html.haml
= content_for :secondary_nav do
  .nav-scroller.bg-white.box-shadow
    .container.d-flex.justify-content-between
      %nav.nav.nav-underline.justify-content-start
        = link_to 'Get Public Link', public_ticket_path(@ticket), class:'nav-link bg-light', target: '_blank'
      %nav.nav.nav-underline.justify-content-end
        = link_to 'Create a New Ticket', new_ticket_path, class:'nav-link bg-light'
        = link_to 'Edit the ticket', edit_ticket_path(@ticket), class:'nav-link bg-light'

.d-flex.align-items-center.p-3.my-3.text-white-50.bg-purple.rounded.box-shadow
  = image_tag 'https://getbootstrap.com/assets/brand/bootstrap-outline.svg', class:'mr-3', width:'28', height:'28'
  .lh-100
    %h3.mb-0.text-white.lh-100
      = @ticket.name
  .ml-auto
    = @ticket.number
.my-3.p-3.bg-white.rounded.box-shadow
  = form_for @ticket do |f|
    = hidden_field_tag :authenticity_token, form_authenticity_token
    %span.mr-2
      %strong Status:
      = f.select :status, @ticket.ticket_status.map{|t| [t.humanize, t]},{}, {class:'', onchange:'this.form.submit()'}
    %span.mr-2
      %strong Priority:
      = f.select :priority, @ticket.ticket_priorities.map{|t| [t.humanize, t]},{prompt: true}, {class:'', onchange:'this.form.submit()'}
    %span.mr-2
      %strong Ticket Type:
      = f.select :ticket_type, @ticket.ticket_types.map{|t| [t.humanize, t]},{prompt: true}, {class:'', onchange:'this.form.submit()'}
  .my-4
    = raw @ticket.description

  .media.text-muted.pt-3
    = image_tag 'https://getbootstrap.com/assets/brand/bootstrap-outline.svg', width:'28', height:'28', class:'mr-2 rounded bg-purple'
    .media-body.mb-0.small.ln-125
      %strong.d-block.text-gray-dark.mb-1
        = ticketit_user.name
      = form_for @ticket.comments.new, html:{class:'d-block'}, remote: true do |f|
        = f.hidden_field :commentable_id, value: @ticket.id
        = f.hidden_field :commentable_type, value: @ticket.class
        .form-group
          = f.text_area :content, class:'form-control'
        = f.submit 'Comment', class:'btn bg-purple text-white'

- comments = @ticket.comments.where.not(id: nil)
.my-3.p-3.bg-white.rounded.box-shadow
  Comments
  %hr
  .comments
    - if comments.any?
      = render comments.order(created_at: :desc)